# Generated by Django 3.0.5 on 2020-06-22 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.IntegerField()),
                ('shelter_id', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='playdate date')),
                ('activity', models.CharField(choices=[('W', 'Walk'), ('P', 'Play'), ('G', 'Groom'), ('T', 'Train')], default='W', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
