# Generated by Django 3.0.5 on 2020-06-25 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200624_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playdate',
            name='user',
        ),
        migrations.AddField(
            model_name='playdate',
            name='profile',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile'),
            preserve_default=False,
        ),
    ]
